parent: "configs/base.yaml"

save_path: "output/omd/debug"

# dataset params:
type: "OMD"
source_path: "data/omd/"
save_step: 1 #2000
eval: True #False # whether select frames for eval
eval_llff: 1 #5 # the step for select frame for eval

# map preprocess
min_depth: 1.0 #0.3
max_depth: 12
invalid_confidence_thresh: 0.0

# state manage
stable_confidence_thres: 200 #5000 #200
unstable_time_window: 150
memory_length: 5

# optimize params:
gaussian_update_iter: 50 #300
gaussian_update_frame:  1
dyna_start_iter: 0 # #4000000 #40
position_lr : 0.01 #0.001
feature_lr : 0.01 #0.001
opacity_lr : 0.01 #0.000
scaling_lr : 0.02
rotation_lr : 0.01 #0.001
dyna_position_lr : 0.1 #0.001
dyna_feature_lr : 0.1 #0.001
dyna_opacity_lr : 0.01 #0.000
dyna_scaling_lr : 0.005 #0.02
dyna_rotation_lr : 0.01 #0.001

use_orb_backend: True
orb_useicp: True

# track params
use_gt_pose: True #False
icp_use_model_depth: True # if False, use dataset depth frame to frame
#icp_matches_threshold: 0.2 # ratio * valie pixels
icp_normal_threshold: 20 # degree
icp_sample_distance_threshold: 0.01 # m
icp_sample_normal_threshold: 0.01 # cos similarity
