parent: "configs/tum_base.yaml"

frame_start: 0
frame_step: 0
frame_num: -1

# dataset params:
source_path: "/hdd2/tum/tum_rtgslam/rgbd_dataset_freiburg3_walking_xyz"
save_path: "//hdd2/output/TUM_RGBD/fr3_walking_xyz"

orb_settings_path: "configs/orb_config/tum3.yaml"