parent: "configs/omd_base.yaml"

frame_start: 0
frame_step: 0
frame_num: -1

# dataset params:
source_path: "//hdd2/OMD/swinging_4_unconstrained"
save_path: "//hdd2/output/omd/swinging_4_unconstrained"

orb_settings_path: "configs/orb_config/omd.yaml"